### ISSUE TITLE
Crashes when using through swift package manager.

### ISSUE THREAD

**Issue by indrajitv** [kizitonwose/CountryPickerView#135]
![Screenshot 2021-01-04 at 2 49 06 PM](https://user-images.githubusercontent.com/11582829/103519732-0cb53900-4e9c-11eb-824a-57513e63a8c6.png)

Thanks.

**Comment by indrajitv** [comment]
In Xcode 12.3, Using SPM. I can reproduce the issue everytime.

**Comment by shanecowherd** [comment]
Same issue here, I wonder if it is something to do with the Project Manifest file not knowing where the bundle is located. I spent a bit of time messing with this before going back to Cocoapods :(

**Comment by kohlab** [comment]
It'd be great if this could be installed with Swift Package Manager. We're getting close to having all our dependencies installable this way; this is an exception.

**Comment by kizitonwose** [comment]
I worked on this for a bit today but could not find a way to make it work with SPM. The current changes are in the `spm` branch in case anyone wants to take a look. Unfortunately, I do not have a lot of time to invest in this at the moment.

**Comment by indrajitv** [comment]
@kizitonwose Any new on this issue?  Just for this pod, I am unable to shift my project onto package manager,

**Comment by devedup** [comment]
It's failing because it's not packaging the bundle correctly for SPM. I've forked it and made it compatible with Swift Package Manager and I did a few other minor tweaks, including using vector pdfs instead of pngs...

https://github.com/devedup/CountryPickerView

**Comment by kohlab** [comment]
This is an excellent development, @devedup. I was able to link my app successfully with your Swift package. Alas it crashes when I try to instantiate a picker. If you enable Issues in your fork, I can provide more detail there rather than cluttering this thread.

**Comment by kizitonwose** [comment]
SPM usage is now fixed in [3.3.0](https://github.com/kizitonwose/CountryPickerView/releases/tag/3.3.0) 🚀

**Comment by federicopolesello** [comment]
Hi @kizitonwose, thanks for your hard work but I'm still having an issue when installing the library through SPM. The error during build is: "Framework not found CountryPickerView".

![Screenshot 2021-10-14 at 11 58 01](https://user-images.githubusercontent.com/6029717/137295876-eb558641-c7e2-4170-825c-50cebea589b8.png)
